from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import json
import os

# Import the existing Intelligence Engine built in Phase 2
from intelligence_core import setup_langchain_agent

app = FastAPI(title="JARVIS Backend Gateway", description="Sovereign AI Mini-Palantir API for India")

print("[JARVIS Gateway] Initializing Sovereign GraphRAG Inference Engine...")
try:
    llm, retriever_tool = setup_langchain_agent()
    # In a full deployment, we'd use AgentExecutor. We map the simplified logic.
except Exception as e:
    print(f"[JARVIS Gateway] Error initializing GraphRAG: {e}")
    llm = None
    retriever_tool = None

# Pydantic Schemas
class QueryRequest(BaseModel):
    query: str
    
class VoiceRequest(BaseModel):
    audio_base64: str
    language: str = "hi-IN"

@app.post("/intelligence")
async def get_intelligence(request: QueryRequest):
    """
    Task 2: Route natural language queries into the Neo4j LlamaIndex array and synthesize with Sarvam-30B.
    """
    if not llm or not retriever_tool:
        raise HTTPException(status_code=503, detail="Inference engine offline.")
        
    try:
        # 1. Extractor Agent logic (using the query direct target mock for pure routing)
        # We extract the main noun via string splitting (for demo routing without a full Agent abstraction)
        target = request.query.split()[-1].replace("?", "").strip()
        
        # 2. Graph Retrieval Path
        context = retriever_tool.run(target)
        
        # 3. Sovereign Inference Synthesis
        prompt_injection = f"Observation: {context}\\nThought: ..."
        response = llm.invoke(prompt_injection)
        
        return {
            "query": request.query,
            "extracted_entities": [target],
            "graph_paths": context,
            "synthesis": response
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/alerts")
async def get_alerts():
    """
    Task 3: Parse the active Threat Matrix JSON cache generated by the background daemon.
    """
    if os.path.exists("threat_matrix.json"):
        with open("threat_matrix.json", "r") as f:
            return json.load(f)
    return {"active_threats": [], "status": "No anomalies detected."}

@app.post("/voice")
async def process_voice(request: VoiceRequest):
    """
    Task 4: WebRTC Integration with Sarvam Saaras/Bulbul models for native linguistic translation.
    Currently mocked to handle schemas dynamically.
    """
    # Placeholder for Sarvam audio processing pipeline
    mocked_transcript = "What are the active threats in Kabul?" if "hi" in request.language else "Translate failure."
    
    return {
        "status": "processing",
        "sarvam_audio_engine": "MOCKED",
        "stt_transcript": mocked_transcript,
        "note": "Requires active Sarvam API keys to translate base64 stream"
    }

if __name__ == "__main__":
    import uvicorn
    # Task 4: Host precisely on port 8080 or 8000 depending on frontend mappings
    uvicorn.run(app, host="0.0.0.0", port=8888)
